project:
  type: book  
  output-dir: docs

book:
  title: "Project Sharknado: Evaluating the Actuarial Risk of Coastal-Origin Atmospheric Tornadoes in the United States"
  author: "Sophia Heinrich"
  page-footer:
    left: "Copyright 2026, Sophia Heinrich"
  chapters:
    - index.qmd
    - intro.qmd
    - methodology.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



